# Generated by Django 4.2.13 on 2024-07-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credentials', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
